In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
vocab_size = 10000

In [5]:
onehot = [one_hot(words,vocab_size)for words in sent]
print(onehot)

[[739, 3526, 9273, 7262], [739, 3526, 9273, 5308], [739, 8483, 9273, 5445], [1553, 6506, 5303, 325, 346], [1553, 6506, 5303, 325, 534], [4581, 739, 4134, 9273, 4377], [6876, 1158, 2655, 325]]


In [6]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np


In [8]:
sent_length = 8
embedded = pad_sequences(onehot,padding='pre',maxlen=sent_length)
print(embedded)

[[   0    0    0    0  739 3526 9273 7262]
 [   0    0    0    0  739 3526 9273 5308]
 [   0    0    0    0  739 8483 9273 5445]
 [   0    0    0 1553 6506 5303  325  346]
 [   0    0    0 1553 6506 5303  325  534]
 [   0    0    0 4581  739 4134 9273 4377]
 [   0    0    0    0 6876 1158 2655  325]]


In [9]:
model = Sequential()
model.add(Embedding(vocab_size,10,input_length=sent_length))
model.compile('adam','mse')

In [10]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [11]:
print(model.predict(embedded))

[[[-0.03363699  0.00906075  0.04514762 -0.01798381  0.02649887
   -0.03426291 -0.00599735 -0.02726623 -0.0476568   0.01220635]
  [-0.03363699  0.00906075  0.04514762 -0.01798381  0.02649887
   -0.03426291 -0.00599735 -0.02726623 -0.0476568   0.01220635]
  [-0.03363699  0.00906075  0.04514762 -0.01798381  0.02649887
   -0.03426291 -0.00599735 -0.02726623 -0.0476568   0.01220635]
  [-0.03363699  0.00906075  0.04514762 -0.01798381  0.02649887
   -0.03426291 -0.00599735 -0.02726623 -0.0476568   0.01220635]
  [-0.00276949  0.02245695 -0.04069524 -0.01847712 -0.0270074
   -0.04358667  0.01180779  0.02978453  0.04031197 -0.00545786]
  [-0.03608032 -0.02996696  0.00359408 -0.01621296  0.01555871
    0.01365456  0.03309066 -0.00844548 -0.00437992 -0.03529546]
  [-0.02704512 -0.01693805  0.02395283  0.0070544   0.0418782
   -0.0007106   0.0262148  -0.00999469  0.02706469  0.03901756]
  [ 0.0259445   0.0401347   0.0119997   0.04025898 -0.04502486
    0.02951677 -0.03553366  0.00979019  0.03436489

In [12]:

embedded[0],model.predict(embedded)[0]

(array([   0,    0,    0,    0,  739, 3526, 9273, 7262], dtype=int32),
 array([[-0.03363699,  0.00906075,  0.04514762, -0.01798381,  0.02649887,
         -0.03426291, -0.00599735, -0.02726623, -0.0476568 ,  0.01220635],
        [-0.03363699,  0.00906075,  0.04514762, -0.01798381,  0.02649887,
         -0.03426291, -0.00599735, -0.02726623, -0.0476568 ,  0.01220635],
        [-0.03363699,  0.00906075,  0.04514762, -0.01798381,  0.02649887,
         -0.03426291, -0.00599735, -0.02726623, -0.0476568 ,  0.01220635],
        [-0.03363699,  0.00906075,  0.04514762, -0.01798381,  0.02649887,
         -0.03426291, -0.00599735, -0.02726623, -0.0476568 ,  0.01220635],
        [-0.00276949,  0.02245695, -0.04069524, -0.01847712, -0.0270074 ,
         -0.04358667,  0.01180779,  0.02978453,  0.04031197, -0.00545786],
        [-0.03608032, -0.02996696,  0.00359408, -0.01621296,  0.01555871,
          0.01365456,  0.03309066, -0.00844548, -0.00437992, -0.03529546],
        [-0.02704512, -0.01693805, 